apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-secrets
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: ""
    keyvaultName: "kv-microservices-plat"
    objects: |
      array:
        - |
          objectName: db-password
          objectType: secret
    tenantID: "dabd0b69-b1f7-44fd-b084-481280986a87"
  secretObjects:
  - secretName: app-secrets
    type: Opaque
    data:
    - objectName: db-password
      key: DB_PASSWORD
